### ISSUE TITLE
Output of HTML/head/body tag deprecation in 1.39

### ISSUE THREAD

**Issue by jdlrobson** [Universal-Omega/Monaco#16]
In 1.39, output of headelement and body/html tags is no longer supported as part of https://phabricator.wikimedia.org/T62846

See https://gerrit.wikimedia.org/r/c/mediawiki/skins/Timeless/+/777826 for an example of how to remove the deprecation warning in MediaWiki 1.39 >=

**Comment by Universal-Omega** [comment]
Thank you! I did #20 for this, but still might need some more work for it.
