### ISSUE TITLE
"Special Pages" toolbox link broken

### ISSUE THREAD

**Issue by HopperMCS** [Universal-Omega/Monaco#24]
It redirects to ```Special:SpecialPage``` instead of ```Special:SpecialPages```. This leads the user to a page not found page. I've been trawling through ```includes/MonacoTemplate.php``` to try and find where the link gets created but can't really find it with the rest of the toolbox stuff in the SIDEBAR section.

**Comment by Universal-Omega** [comment]
Should be fixed now. You'll have to rebuild localisation cache once you update, since it is in the message, MediaWiki:Monaco-toolbox.
