### ISSUE TITLE
Failed bugfix

### ISSUE THREAD

**Issue by WikiMANNia** [Universal-Omega/Monaco#31]
While trying to fix an interference with the Theme extension (https://github.com/Universal-Omega/Monaco/pull/30/commits/23526a23f1472bae9363ee6017988bb57d66ae4c#diff-e56139e298e20e78c2fae614a57f52aa1473ad18537470dffe0d2166a8d9b90a), I changed the key 'theme' to 'theme_monaco' in the file MonacoHooks.php in line 82 and neglected to do the same in the file SkinMonaco.php in line 79. :-(

What to do:
Change the key from 'theme' to 'theme_monaco' in the file SkinMonaco.php in line 79.

I apologize for this negligence.

**Comment by WikiMANNia** [comment]
Sorry: Another key has to be changed! :-(

What to do:
Change the key from 'theme' to 'theme_monaco' in the file MonacoHooks.php in line 78.

I apologize for this negligence.

**Comment by Universal-Omega** [comment]
Fixed

**Comment by WikiMANNia** [comment]
The first pull request was tested well.

Then the interference with the extension theme was somehow confusing. The second pull request was therefore premature.

Today I tested all versions (1.35, 1.39 and 1.41) and it seems that everything works fine now (again) ;-)

Have a good day! :-)
